### ISSUE TITLE
Make into vendorlib

### ISSUE THREAD

**Issue by gcjurgiel** [rambunction4330/librmb#18]

**Comment by theVerySharpFlat** [comment]
Currently, the maven repo for the vendordep is being hosted. However, I have yet to test it

**Comment by theVerySharpFlat** [comment]
@gcjurgiel If you feel like it, you can test it on your end. The json url is here https://rambunction4330.github.io/librmb/vendordep/LibRmb.json.

**Comment by gcjurgiel** [comment]
It doesn't work right now for a few reasons. First is that you are publishing to `repo/release/` but the vendor json just says `repo`, second the json says that we built artifacts for linux when there art any, and third even after fixing that it still can't find the header possibly because we forgo having an` include` and` src` directory.

**Comment by gcjurgiel** [comment]
Also, as I'm starting to write more documentation, what is the proper casing of librmb. The repo name is all lowercase though you used pascal case in the vendor library and I could also see a formatting like libRMB

**Comment by theVerySharpFlat** [comment]
> Also, as I'm starting to write more documentation, what is the proper casing of librmb? The repo name is all lowercase though you used pascal case in the vendor library and I could also see a formatting like libRMB.

The library name should be all lowercase. I just don't know what the frc standard is. I'll look into it

**Comment by theVerySharpFlat** [comment]
> It doesn't work right now for a few reasons. First is that you are publishing to `repo/release/` but the vendor json just says `repo`, second the json says that we built artifacts for linux when there art any, and third even after fixing that it still can't find the header possibly because we forgo having an` include` and` src` directory.

I believe that this issue is now fixed
